name: Docker Image - ${GITHUB_REPOSITORY} - $GITHUB_REPOSITORY

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master

    - name: Show env
      run: env

    - name: Show GITHUB_RUN_NUMBER
      run: echo $GITHUB_RUN_NUMBER

    - name: Build tag
      run: docker build -t ${GITHUB_REPOSITORY}:$GITHUB_RUN_NUMBER .

    - name: Tag :latest
      run: docker tag ${GITHUB_REPOSITORY}:$GITHUB_RUN_NUMBER ${GITHUB_REPOSITORY}:latest

    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push tag to docker hub
      uses: actions-hub/docker@master
      with:
        args: push ${GITHUB_REPOSITORY}:$GITHUB_RUN_NUMBER

    - name: Push latest to docker hub
      uses: actions-hub/docker@master
      with:
        args: push ${GITHUB_REPOSITORY}:latest