name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master

    - name: Build tag
      env:
        now: $(date +%s)
      run: docker build -t ${GITHUB_REPOSITORY}:$now .

    - name: Tag :latest
      run: docker tag ${GITHUB_REPOSITORY}:$now ${GITHUB_REPOSITORY}:latest

    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push tag to docker hub
      uses: actions-hub/docker@master
      with:
        args: push ${GITHUB_REPOSITORY}:$now

    - name: Push latest to docker hub
      uses: actions-hub/docker@master
      with:
        args: push ${GITHUB_REPOSITORY}:latest